# Chat formats, based on permissions.
chat:
  # "admin" and "vip" are examples, you can use anything you want instead.
  # Chat format that requires the "yoctochat.admin" permission.
  admin: "§c<[Admin] {DISPLAY_NAME}> §r{MESSAGE}"
  # Chat format that requires the "yoctochat.vip" permission.
  vip: "§6<[VIP] {DISPLAY_NAME}> §r{MESSAGE}"

  # The last entry is the default chat format, used by everyone else.
  default: "<{DISPLAY_NAME}> {MESSAGE}"

# Private messages configuration.
private_messages:
  # Sent when the command is used without enough arguments.
  usage: "/msg <player> <message>"
  # Sent when the reply command is used with no argument.
  reply_usage: "/r <message>"
  # Message sent to the sender.
  sent: "§7to {DISPLAY_NAME}: {MESSAGE}"
  # Message sent to the receiver.
  received: "§7from {DISPLAY_NAME}: {MESSAGE}"
  # Message sent to the sender when the receiver is offline.
  error_not_found: "§cPlayer {RECEIVER} not found."
  # Message sent to the sender when there is no one to reply to.
  error_no_reply: "§cNo one to reply to."

# Discord configuration.
discord:
  # If enabled, all public messages will be sent to the specified Discord channel.
  enabled: false
  # Your private bot token.
  bot_token: "..."
  # Id of the channel where the messages should be sent.
  channel_id: 123456
